#!/usr/bin/python
#-*-coding:utf8;-*-
import logging
import os
import sys

PROJECT_NAME = 'itsbox_d_operator'
PROJECT_DIR = [path for path in sys.path if len(path)>17 and str.lower(path[-17:])==PROJECT_NAME][0]

LOG_LEVEL = logging.DEBUG
LOG_FILE_DIR = os.path.join(PROJECT_DIR, 'logs')
LOG_FILE_PREFIX = 'operator'
LOG_FILE_ALLINONE = False
LOG_FILE_ROTATION = False
LOG_FILE_MAX_BYTES = 1024 * 1024 * 10
LOG_FILE_MAX_COUNT = 10

RABBITMQ_IP = '127.0.0.1'
RABBITMQ_PORT = 5672
RABBITMQ_VHOST = '/'
RABBITMQ_USER = 'itsbox'
RABBITMQ_PASS = 'itsbox'
RABBITMQ_QNAME_MGMT_IN = 'ITSBOX.D.MGMT_IN'
RABBITMQ_QNAME_MGMT_OUT = 'ITSBOX.D.MGMT_OUT'
RABBITMQ_QNAME_MSG_IN = 'ITSBOX.D.MSG_IN'
RABBITMQ_QNAME_MSG_OUT = 'ITSBOX.D.MSG_OUT'

MAX_WORKER_PER_NODE = 100
MAX_THREAD_PER_WORKER = 100
WORKER_COUNT = 2
THREAD_COUNT = 5
WORKER_WATCHER_INTERVAL = 5
MANAGER_REQUEST_TIMEOUT_PER_WORKER = 3

WEBSOCKET_MGMT_SERVER_BOOT = True
WEBSOCKET_MGMT_SERVER_PORT = 8081

RULE_MODULE_BASE = "itsbox.operator"
